Angular 17 (#2277)
* Update to Angular 17

* Fix firebase queries

Was getting this error using rxfire doc() and collectionSnapshots() methods:

```
FirebaseError: Expected type 'dh', but it was: a custom DocumentReference object
```

Using AngularFire getDoc() and getDocs() works better for some reason.

* Fix adif export

Wasn't correctly mapping across object properties.

* Make the QSO list realtime again